DROP TABLE IF EXISTS users, pets;

CREATE TABLE pets (
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    species VARCHAR(256)
);

CREATE TABLE users (
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(256),
    age INT,
    pet_id BIGINT
);

ALTER TABLE users ADD FOREIGN KEY (pet_id) REFERENCES pets(id);